### ISSUE TITLE
killmessages

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_KoeniglicherKampf.Altis#20]
funktionieren nicht

**Comment by McDiod** [comment]
Muss auf client ausgeführt werden. "Killed" EH funktioniert nur, wo die Einheit lokal ist.

**Comment by nomisum** [comment]
Killed EH ist in ACE buggy, d.h. killer ist oft identisch mit victim auch bei Abschüssen.

ACE Ticket: https://github.com/acemod/ACE3/issues/3111

Glaube das Problem hängt damit zusammen, dass das Vanilla Game scripted ammo nicht als Killer identifizieren kann.

> As far as I know there is no way for us to tell the engine that scripted submunition ammo or scripted damage is from a player. So the killed events and score tracking will be wrong with ACE and there is nothing we can do about it.

Eingeführt also mit den ganzen Schrapnells und Splittern, die oft zum Tod führen.

**Comment by McDiod** [comment]
Workaround. Nachricht ist jetzt nur noch "_x was killed."

**Comment by McDiod** [comment]
Error: No unit was killed

**Comment by McDiod** [comment]
fixed?

**Comment by McDiod** [comment]
nope
