### ISSUE TITLE
Lootspawn beschleunigen

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_KoeniglicherKampf.Altis#28]
[Sleep](https://github.com/gruppe-adler/TvT_KoeniglicherKampf.Altis/blob/master/loot/lootInit.sqf#L88) im lootspawn script ist derzeit nötig, weil der weaponholder sonst bei [0,0,0] spawnt.

**Comment by phumberdroz** [comment]
"Loot spawning completed in 68.2188 seconds. Spawned loot in 4485 positions."
"Loot spawning completed in 73.64 seconds. Spawned loot in 4882 positions."
"Loot spawning completed in 45.688 seconds. Spawned loot in 3410 positions."

**Comment by phumberdroz** [comment]
habs nicht schneller bekommen vorerst.. :)

**Comment by McDiod** [comment]
Ah cool, das ist ja 2-3 mal so schnell.
Wieviel davon spawnt in deiner Version bei [0,0,0]? Vorher waren's immer knapp 10% glaub ich.

Wird [hier](https://github.com/gruppe-adler/TvT_KoeniglicherKampf.Altis/blob/master/loot/lootInit.sqf#L92) geloggt, wenn der Debugmodus an ist.

**Comment by phumberdroz** [comment]
"Buggy loot spawns: 31"
"Buggy loot spawns: 36"
"Buggy loot spawns: 27"
