### ISSUE TITLE
if group number does not go off

### ISSUE THREAD

**Issue by phumberdroz** [gruppe-adler/TvT_KoeniglicherKampf.Altis#29]
So for example we have 9 players and 2 player teams one is left and does not get teleported.

**Comment by McDiod** [comment]
Log:

> 23:04:14 "Team randomizer starting..."
> 23:04:14 "Randomizing 9 players into 4 teams"
> 23:04:14 "Teamleaders selected: ["Isamu","nomisum","XiviD","Panda"]"
> 23:04:14 "DerZade added to Isamu's team."
> 23:04:14 "Xenon // Ernst added to nomisum's team."
> 23:04:14 "stefan added to XiviD's team."
> 23:04:14 "Fridelcastro added to Panda's team."

Quelle:
https://github.com/gruppe-adler/TvT_KoeniglicherKampf.Altis/blob/master/setup/randomTeams.sqf#L27

Fehler:
Es muss natürlich nach oben gerundet werden. Ich fix es später.
