### ISSUE TITLE
Limit Spawn radius to playareacenter

### ISSUE THREAD

**Issue by phumberdroz** [gruppe-adler/TvT_KoeniglicherKampf.Altis#32]
Um so etwas wie dem was gestern passiert ist vorzubeugen evtl den Spawn auf 500 - 1000 meter radius limitieren als center PLAYAREACENTER?

Oder ne andere Idee?

![](http://forum.gruppe-adler.de/uploads/files/1456225153437-2016-02-22_00005.jpg)

**Comment by McDiod** [comment]
Ich wollte bei Zeiten einen Mindestabstand zur nächsten Küste einbauen (1km oder so?). Das würde das Problem zwar nicht komplett verhindern, aber zumindest schonmal sehr viel unwahrscheinlicher machen.

Nachteil bei Spawn in der Nähe des Mittelpunkts ist natürlich, dass die Spieler durchschnittlich dichter zusammen starten und dadurch früher sterben -> einige Leute lange im Spectator hocken.

**Comment by phumberdroz** [comment]
Quasi 1km vom center aus gesehen ? Ja ich denke das würde helfen.
